itemDef
{
    name                keyBindStatus
    group               none
    ownerdraw           250 // UI_KEYBINDSTATUS
    text                @MENUS2_BLANK_1
    rect                320 425 0 0
    textStyle           0
    font                2
    textscale           .8
    textalign           ITEM_ALIGN_CENTER
    forecolor           .235 .882 .847 1
    visible             0
    decoration
}

itemDef
{
    name                slider_message
    group               none
    text                @MENUS0_MOVE_THE_SLIDER_TO_INCREASE
    rect                320 425 0 0
    textStyle           0
    font                2
    textscale           .8
    textalign           ITEM_ALIGN_CENTER
    visible             0
    decoration
}

itemDef
{
    name                yesno_message
    group               none
    text                @MENUS0_CLICK_ON_FIELD_TO_TOGGLE
    rect                320 425 0 0
    textStyle           0
    font                2
    textscale           .8
    textalign           ITEM_ALIGN_CENTER
    visible             0
    decoration
}

itemDef
{
    name                multi_message
    group               none
    text                @MENUS0_CLICK_ON_FIELD_TO_CHANGE
    rect                320 425 0 0
    textStyle           0
    font                2
    textscale           .8
    textalign           ITEM_ALIGN_CENTER
    visible             0
    decoration
}
